export const WORKFLOW_ROUTE_KEYS = [
  "capture.entry",
  "capture.suggest",
  "capture.editSuggestion",
  "capture.rejectSuggestion",
  "capture.acceptAsTask",
  "signal.ingest",
  "signal.triage",
  "signal.convert",
  "planning.completeTask",
  "planning.deferTask",
  "planning.rescheduleTask",
  "approval.requestEventSync",
  "approval.requestOutboundDraftExecution",
  "approval.approveOutboundAction",
  "job.create",
  "job.recordRun",
  "job.inspectRun",
  "job.list",
  "job.listHistory",
  "job.retry",
  "checkpoint.create",
  "checkpoint.inspect",
  "checkpoint.keep",
  "checkpoint.recover",
  "activity.list",
] as const;

export type WorkflowRouteKey = (typeof WORKFLOW_ROUTE_KEYS)[number];
